### ISSUE TITLE
Need 1.0.8 release

### ISSUE THREAD

**Issue by gregfullman** [drone/ff-dotnet-server-sdk#11]
I'd like to get the changes from #9 incorporated into a nuget package that I can pull in via automation build. If we could get that bugfix released, that'd be great, thanks!

**Comment by milos85vasic** [comment]
@gregfullman I will release the .net SDK version now. It will be available on NuGet soon. I will ping you one more time once it is ready.

**Comment by milos85vasic** [comment]
@gregfullman I have just released version 1.0.8. Best regards!
